---
title: "Lipid Data Initial Graphs"
author: "Alex Ostrovsky"
date: "10/21/2018"
output: html_document
---

```{r, include=FALSE}
setwd("/Users/alexanderostrovsky/Desktop/McCurdy/2018-group-projects-mccurdy/LipidData/LipidData/CSVs from given data/Processed CSVs (format and LOQ)/Modified LOQ/")
knitr::opts_chunk$set(error = TRUE)
```

```{r include=FALSE, eval=TRUE}


#install.packages("vegan", repos = "https://cran.r-project.org/src/contrib/vegan_2.5-2.tar.gz")
#install.packages("MASS", repos = "https://cran.r-project.org/src/contrib/MASS_7.3-50.tar.gz")
library("vegan")
library("MASS")

#install.packages("gplots", repos = "https://cran.r-project.org/src/contrib/gplots_3.0.1.tar.gz")
#install.packages("RColorBrewer", repos = "https://cran.r-project.org/src/contrib/RColorBrewer_1.1-2.tar.gz")
#install.packages("dendextend",repos = "https://cran.r-project.org/src/contrib/dendextend_1.8.0.tar.gz")
library("gplots")
library("RColorBrewer")
library("dendextend")
#load packages
```

```{r include=F}

DGs1.2 <- read.csv("1.2DGs.changed LOQ.csv", head = TRUE, row.names = 1)
AC <- read.csv("AC.formatted.noloq.csv", head = TRUE, row.names = 1)
Cer <- read.csv("Cerimides.changedLOQ.csv", head = TRUE, row.names = 1)
DGs1.3 <- read.csv("CM033018 1-3DGs.changedLOQ.csv", head = TRUE, row.names = 1)
dh <- read.csv("dhCer.changedLOQ.csv", head = TRUE, row.names = 1)
Glu <- read.csv("GluCer.changedLOQ.csv", head = TRUE, row.names = 1)
hex <- read.csv("hexosylCer.changedLOQ.csv", head = TRUE, row.names = 1)
Lac <- read.csv("LacCer.changedLOQ.csv", head = TRUE, row.names = 1)
mye <- read.csv("Sphingomyelins.formatted.noloq.csv", head = TRUE, row.names = 1)
sine <- read.csv("Sphingosine.formatted.noloq.editfordismatrix.csv", header = TRUE, row.names = 1)
TAG <- read.csv("TAG.changedLOQ.csv", head = TRUE, row.names = 1)

ALL <- cbind(AC, Cer, DGs1.2, DGs1.3, dh, Glu, hex, Lac, mye, sine, TAG)

plotlist <- list(DGs1.2, DGs1.3, TAG, AC, dh, Glu, hex, Lac, sine, Cer, mye, ALL)
plotname <- c("DGs1.2", "DGs1.3", "TAG", "AC", "dh", "Glu", "hex", "Lac", "sine", "Cer", "mye", "ALL")

```

```{r Dissimilarity, echo=F, results = 'hide'}
x <-  1
par(mfrow = c(2,2))
for (n in plotlist){
  DGs.dis <- vegdist(n)
  DGs.mds <- isoMDS(DGs.dis, k=2) 
  stressplot(DGs.mds, DGs.dis, main = plotname[x])
  x <- x+1
}
```

```{r Ordination, echo = F, results='hide'}
x <- 1
par(mfrow = c(1,2))
for(n in plotlist){
  DGs.dis <- vegdist(n)
  DGs.mds <- isoMDS(DGs.dis, k=2) 
  Targets <- as.data.frame(rownames(n))
  Targets$Group <- factor(c(rep("one",8),rep("two",5),rep("three",8),rep("four",8),rep("five",7))) 
  colnames(Targets) <- c("ID","Group")
  par(mgp = c(2.5, 1, 0))
  grp=as.character(Targets$Group)
  fig<-ordiplot(DGs.mds, main = paste("Samples in Lipid abundance Space: ", plotname[x], sep = ""), display = "sites", ylab= "nMDS Dimension2", xlab="nMDS Dimension 1", font.lab=2, font.axis=2, cex.axis = 0.7, type = "none", cex.main=.9)
    ordiellipse(DGs.mds,groups=grp,label=FALSE, lwd=2,  show.groups=grp[1:36], col=c("blue", "green", "pink", "gold","orange"), draw="lines")
  #circles
  points(fig, "sites", pch=c(rep(15,2),rep(19,4),15,19,15,19,rep(15,3),rep(19,3),rep(15,5),rep(19,2), 15, rep(19,3), rep(15,3), rep(19,2), rep(15,2), rep(19,5)), col=c(rep("pink",8),rep("orange",5),rep("gold",8),rep("green",8),rep("blue",7)), cex=1.5)
  
  legend("bottomleft", legend = c("Ln/CTR-CTR", "Ln/CTR-HFD","Ln/HFD-CTR","Ln/HFD-HFD","Ob/HFD-CTR"),
         col = c("pink","orange","gold","green","blue"), pch=c(19), cex = 0.5)
  
  legend("topright", legend = c("Male","Female"),
         col = "blue", pch=c(15 ,19), cex = 0.5)
  x <- x+1
}
```

```{r Heat, echo = F, results = 'hide', message = F}
sink("/dev/null")
x <- 1
for(n in plotlist){
  DGs.dis <- vegdist(n)
  DGs.mds <- isoMDS(DGs.dis, k=2) 
  Targets <- as.data.frame(rownames(n))
  Targets$Group <- factor(c(rep("one",8),rep("two",5),rep("three",8),rep("four",8),rep("five",7))) 
  colnames(Targets) <- c("ID","Group")
  otu.env <- Targets
  #OTU = operational taxonomic unit

  DGs.s <- t(t(scale(n)))
  
  DGs.d1 <- dist(DGs.s, method = "euclidean", diag = FALSE, upper = TRUE)
  #Calculate multivariate dissimilarity for all pairs w/ Euclidean distance, matrix
  
  
  DGs.c1 <- hclust(DGs.d1, method = "ward.D2", members = NULL)
  
  DGs_pal <- colorRampPalette(c("green","yellow","red")) (n = 299)
  
  par(cex.main=0.5, cex.axis=0.5, font=2, font.axis=2) # Shrink title fonts on plot
  par(mar=c(1,1,1,1))
  

  heatmap.2(DGs.s, density.info="none", trace="none", scale="none",
            col = DGs_pal, cexRow=0.5,cexCol=0.75,
            margins=c(3,13), lwid=c(.8,3), lhei=c(.8,3), srtCol=45, adjCol=c(1,1), keysize=1.3, main = plotname[x])
  x <- x+1
  #Heatmap!!
}

```