---
title: "specific significance"
author: "Alex Ostrovsky"
date: "11/28/2018"
output: html_document
---

```{r directory, include=FALSE}
setwd("/Users/alexanderostrovsky/Desktop/McCurdy/2018-group-projects-mccurdy/LipidData/LipidData/CSVs from given data/Processed CSVs (format and LOQ)/Modified LOQ/")
knitr::opts_chunk$set(error = TRUE)
```

```{r libraries, include=FALSE, eval=TRUE}

library(tidyverse)
#install.packages("vegan", repos = "https://cran.r-project.org/src/contrib/vegan_2.5-2.tar.gz")
#install.packages("MASS", repos = "https://cran.r-project.org/src/contrib/MASS_7.3-50.tar.gz")
library("vegan")
library("MASS")

#install.packages("gplots", repos = "https://cran.r-project.org/src/contrib/gplots_3.0.1.tar.gz")
#install.packages("RColorBrewer", repos = "https://cran.r-project.org/src/contrib/RColorBrewer_1.1-2.tar.gz")
#install.packages("dendextend",repos = "https://cran.r-project.org/src/contrib/dendextend_1.8.0.tar.gz")
library("gplots")
library("RColorBrewer")
library("dendextend")
#load packages
```

```{r data import, include=F}
metadata <- as.tibble(read.table("../../2018-group-projects-mccurdy/RNAseq Analysis/RNAseq Analysis/metadata.txt", header = TRUE)[c(2, 4:15, 17:25, 27:40),2:4])
metadata <- metadata %>% mutate(.,"Organism" = rownames(.))
metadata <- metadata %>% mutate(.,"combinations" = paste(M_Diet, PW_Diet, sep = "."))
metadata$combinations <- as.factor(metadata$combinations)
setwd("../../2018-group-projects-mccurdy/LipidData/LipidData/CSVs from given data/Processed CSVs (format and LOQ)/Modified LOQ/")
DGs1.2 <- cbind(metadata[,5], read.csv("1.2DGs.changed LOQ.csv", head = TRUE, row.names = 1))
AC <- cbind(metadata[,5],read.csv("AC.formatted.noloq.csv", head = TRUE, row.names = 1))
Cer <- cbind(metadata[,5],read.csv("Cerimides.changedLOQ.csv", head = TRUE, row.names = 1))
DGs1.3 <- cbind(metadata[,5],read.csv("CM033018 1-3DGs.changedLOQ.csv", head = TRUE, row.names = 1))
dh <- cbind(metadata[,5],read.csv("dhCer.changedLOQ.csv", head = TRUE, row.names = 1))
Glu <- cbind(metadata[,5],read.csv("GluCer.changedLOQ.csv", head = TRUE, row.names = 1))
hex <- cbind(metadata[,5],read.csv("hexosylCer.changedLOQ.csv", head = TRUE, row.names = 1))
Lac <- cbind(metadata[,5],read.csv("LacCer.changedLOQ.csv", head = TRUE, row.names = 1))
mye <- cbind(metadata[,5],read.csv("Sphingomyelins.formatted.noloq.csv", head = TRUE, row.names = 1))
sine <- cbind(metadata[,5],read.csv("Sphingosine.formatted.noloq.editfordismatrix.csv", header = TRUE, row.names = 1))
TAG <- cbind(metadata[,5],read.csv("TAG.changedLOQ.csv", head = TRUE, row.names = 1))
plotlist <- list(DGs1.2, DGs1.3, TAG, AC, dh, Glu, hex, Lac, sine, Cer, mye)
plotname <- c("DGs1.2", "DGs1.3", "TAG", "AC", "dh", "Glu", "hex", "Lac", "sine", "Cer", "mye")
```

```{r anova AC, echo = F}
n <- colnames(AC[, 2:13])
acsig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(AC[,x])~AC$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    acsig[1,t] <- x
    acsig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova Cer, echo = F}
n <- colnames(Cer[, 2:10])
cersig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(Cer[,x])~Cer$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    cersig[1,t] <- x
    cersig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova DGs1.2, echo = F}
n <- colnames(DGs1.2[, 2:25])
DGs1.2sig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(DGs1.2[,x])~DGs1.2$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    DGs1.2sig[1,t] <- x
    DGs1.2sig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova DGs1.3, echo = F}
n <- colnames(DGs1.3[, 2:9])
DGs1.3sig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(DGs1.3[,x])~DGs1.3$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    DGs1.3sig[1,t] <- x
    DGs1.3sig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova dh, echo = F}
n <- colnames(dh[, 2:6])
dhsig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(dh[,x])~dh$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    dhsig[1,t] <- x
    dhsig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova Glu, echo = F}
n <- colnames(Glu[, 2:7])
Glusig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(Glu[,x])~Glu$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    Glusig[1,t] <- x
    Glusig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova hex, echo = F}
n <- colnames(hex[, 2:9])
hexsig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(hex[,x])~hex$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    hexsig[1,t] <- x
    hexsig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova lac, echo = F}
n <- colnames(Lac[, 2:8])
lacsig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(Lac[,x])~Lac$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    lacsig[1,t] <- x
    lacsig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova mye, echo = F}
myesig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(mye[,x])~mye$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    myesig[1,t] <- x
    myesig[2,t] <- sig
    t <- t+1
  }
}
```

```{r anova tag, echo = F}
n <- colnames(TAG[, 2:28])
TAGsig <- data.frame(nrow = 2)
t <- 1
for(x in n){
  print(x)
  ano <- anova(aov(log10(TAG[,x])~TAG$combinations))
  print(ano)
  if(ano$`Pr(>F)` < 0.05){
    sig <- round(as.double(ano$`Pr(>F)`[1]),5)
    TAGsig[1,t] <- x
    TAGsig[2,t] <- sig
    t <- t+1
  }
}
```