---
title: "Factorial ANOVA lipids"
author: "Alex Ostrovsky"
date: "11/18/2018"
output:
  html_document: default
  pdf_document: default
---

```{r Data and library import, echo = F, include = F}
library(tidyverse)
library(grid)
library(gridExtra)
library(nlme)
library(plotrix)
library("knitr")
metadata <- as.tibble(read.table("/Users/alexanderostrovsky/Desktop/McCurdy/2018-group-projects-mccurdy/RNAseq Analysis/RNAseq Analysis/metadata.txt", header = T, sep = '\t')[c(2, 4:15, 17:25, 27:40),])
colnames(metadata) <- c("UO.ID", "Group", "M_BM", "M_Diet", "PW_Diet", "Sex")
setwd("/Users/alexanderostrovsky//Desktop/McCurdy/2018-group-projects-mccurdy/LipidData/LipidData/CSVs from given data/Processed CSVs (format and LOQ)/Modified LOQ/")
DGs1.2 <- as.tibble(read.csv("1.2DGs.changed LOQ.csv", head = TRUE))
DGs1.2 <- cbind(metadata, DGs1.2[,2:25])
AC <- as.tibble(read.csv("AC.formatted.noloq.csv", head = TRUE))
AC <- cbind(metadata, AC[,2:13])
Cer <- as.tibble(read.csv("Cerimides.changedLOQ.csv", head = TRUE))
Cer <- cbind(metadata, Cer[,2:10])
DGs1.3 <- as.tibble(read.csv("CM033018 1-3DGs.changedLOQ.csv", head = TRUE))
DGs1.3 <- cbind(metadata, DGs1.3[,2:9])
dh <- as.tibble(read.csv("dhCer.changedLOQ.csv", head = TRUE))
dh <- cbind(metadata, dh[,2:6])
Glu <- as.tibble(read.csv("GluCer.changedLOQ.csv", head = TRUE))
Glu <- cbind(metadata, Glu[,2:8])
hex <- as.tibble(read.csv("hexosylCer.changedLOQ.csv", head = TRUE))
hex <- cbind(metadata, hex[,2:9])
Lac <- as.tibble(read.csv("LacCer.changedLOQ.csv", head = TRUE))
Lac <- cbind(metadata, Lac[,2:8])
mye <- as.tibble(read.csv("Sphingomyelins.formatted.noloq.csv"))
mye <- cbind(metadata, mye[,2:14])
sine <- as.tibble(read.csv("Sphingosine.formatted.noloq.editfordismatrix.csv", header = TRUE))
sine <- cbind(metadata, sine[,2])
TAG <- as.tibble(read.csv("TAG.changedLOQ.csv", head = TRUE))
TAG <- cbind(metadata, TAG[,2:28])

```

# AC data

```{r AC, echo = F, message = F}
ACmeans <- AC[,c(4,5,7:18)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
ACse <- AC[,c(4,5,7:18)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
ACsummary <- merge(ACmeans, ACse, by = c("M_Diet", "PW_Diet"))
nms <- names(ACsummary)
for(i in 3:14){
  n = i + 12
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(ACsummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Acylcarnitine") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=ACsummary[,i]+ACsummary[,n], ymin=ACsummary[,i]-ACsummary[,n]), width=.1))
}
```

# Cer data

```{r Cer, echo = F, message = F}
Cermeans <- Cer[,c(4,5,7:15)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
Cerse <- Cer[,c(4,5,7:15)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
Cersummary <- merge(Cermeans, Cerse, by = c("M_Diet", "PW_Diet"))
nms <- names(Cersummary)
for(i in 3:11){
  n = i + 9
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(Cersummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Ceramide") + theme(plot.title =element_text(hjust = 0.5)) +
    geom_errorbar(aes_string(ymax=Cersummary[,i]+Cersummary[,n], 
                             ymin=Cersummary[,i]-Cersummary[,n]), width=.1))
}
```

# DGs1.2 data

```{r DGs1.2, echo = F, message = F}
DGs1.2means <- DGs1.2[,c(4,5,7:30)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
DGs1.2se <- DGs1.2[,c(4,5,7:30)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
DGs1.2summary <- merge(DGs1.2means, DGs1.2se, by = c("M_Diet", "PW_Diet"))
nms <- names(DGs1.2summary)
for(i in 3:26){
  n = i + 24
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(DGs1.2summary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "1.2 Diacylglycerol") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=DGs1.2summary[,i]+DGs1.2summary[,n],
                             ymin=DGs1.2summary[,i]-DGs1.2summary[,n]), width=.1))
}
```

# DGs1.3 data

```{r DGs1.3, echo = F, message = F}
DGs1.3means <- DGs1.3[,c(4,5,7:14)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
DGs1.3se <- DGs1.3[,c(4,5,7:14)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
DGs1.3summary <- merge(DGs1.3means, DGs1.3se, by = c("M_Diet", "PW_Diet"))
nms <- names(DGs1.3summary)
for(i in 3:10){
  n = i + 8
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(DGs1.3summary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "1.3 Diacylglycerol") + theme(plot.title =element_text(hjust = 0.5)) +
    geom_errorbar(aes_string(ymax=DGs1.3summary[,i]+DGs1.3summary[,n],
                             ymin=DGs1.3summary[,i]-DGs1.3summary[,n]), width=.1))
}
```

# dh data

```{r dh, echo = F, message = F}
dhmeans <- dh[,c(4,5,7:11)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
dhse <- dh[,c(4,5,7:11)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
dhsummary <- merge(dhmeans, dhse, by = c("M_Diet", "PW_Diet"))
nms <- names(dhsummary)
for(i in 3:7){
  n = i + 5
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(dhsummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Dihydroceramide") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=dhsummary[,i]+dhsummary[,n], 
                             ymin=dhsummary[,i]-dhsummary[,n]), width=.1))
}
```

# Glu data

```{r Glu, echo = F, message = F}
Glumeans <- Glu[,c(4,5,7:13)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
Gluse <- Glu[,c(4,5,7:13)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
Glusummary <- merge(Glumeans, Gluse, by = c("M_Diet", "PW_Diet"))
nms <- names(Glusummary)
for(i in 3:9){
  n = i + 7
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(Glusummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Glucosylceramide") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=Glusummary[,i]+Glusummary[,n], 
                             ymin=Glusummary[,i]-Glusummary[,n]), width=.1))
}
```

# Hex data

```{r Hex, echo = F, message = F}
hexmeans <- hex[,c(4,5,7:14)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
hexse <- hex[,c(4,5,7:14)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
hexsummary <- merge(hexmeans, hexse, by = c("M_Diet", "PW_Diet"))
nms <- names(hexsummary)
for(i in 3:10){
  n = i + 8
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(hexsummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Hexosylceramide") + theme(plot.title =element_text(hjust = 0.5)) +
    geom_errorbar(aes_string(ymax=hexsummary[,i]+hexsummary[,n], 
                             ymin=hexsummary[,i]-hexsummary[,n]), width=.1))
}
```

# Lac data

```{r Lac, echo = F, message = F}
Lacmeans <- Lac[,c(4,5,7:13)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
Lacse <- Lac[,c(4,5,7:13)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
Lacsummary <- merge(Lacmeans, Lacse, by = c("M_Diet", "PW_Diet"))
nms <- names(Lacsummary)
for(i in 3:9){
  n = i + 7
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(Lacsummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Lactosylceramide") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=Lacsummary[,i]+Lacsummary[,n], 
                             ymin=Lacsummary[,i]-Lacsummary[,n]), width=.1))
}
```

# Mye data

```{r Mye, echo = F, message = F}
myemeans <- mye[,c(4,5,7:19)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
myese <- mye[,c(4,5,7:19)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
myesummary <- merge(myemeans, myese, by = c("M_Diet", "PW_Diet"))
nms <- names(myesummary)
for(i in 3:15){
  n = i + 11
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(myesummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Sphingomyelin") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=myesummary[,i]+myesummary[,n], 
                             ymin=myesummary[,i]-myesummary[,n]), width=.1))
}
```

# Sine data

```{r sine, echo = F, message = F}
sinemeans <- sine[,c(4,5,7)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
sinese <- sine[,c(4,5,7)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
sinesummary <- merge(sinemeans, sinese, by = c("M_Diet", "PW_Diet"))
nms <- names(sinesummary)
for(i in 3){
  n = i + 1
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(sinesummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
   labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Sphingosine") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=sinesummary[,i]+sinesummary[,n], 
                             ymin=sinesummary[,i]-sinesummary[,n]), width=.1))
}
```

# TAG data

```{r TAG, echo = F, message = F}
TAGmeans <- TAG[,c(4,5,7:33)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(mean))
TAGse <- TAG[,c(4,5,7:33)] %>% group_by(M_Diet, PW_Diet) %>% summarize_all(funs(std.error))
TAGsummary <- merge(TAGmeans, TAGse, by = c("M_Diet", "PW_Diet"))
nms <- names(TAGsummary)
for(i in 3:29){
  n = i + 27
  lab <- paste(gsub("_", " ", str_sub(nms[i], 2, -3)), "(pmol)", " ")
  print(ggplot(TAGsummary, aes(x = M_Diet, color = PW_Diet, group = PW_Diet), aes_string(y = nms[i])) +
    geom_point(aes_string(y = nms[i])) +
    geom_line(aes_string(y = nms[i], group = nms[2])) +
    theme_classic() + 
    theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="gray47"))+
    labs(x = "Maternal Diet", y = lab, color = "Juv. Diet", title = "Triacylglycerol") + theme(plot.title =element_text(hjust = 0.5)) + 
    geom_errorbar(aes_string(ymax=TAGsummary[,i]+TAGsummary[,n], 
                             ymin=TAGsummary[,i]-TAGsummary[,n]), width=.1))
}
```
